# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('structure', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(db_column='Job_ID', primary_key=True, serialize=False)),
                ('job_name', models.CharField(db_column='Job_Name', max_length=45)),
                ('date_submitted', models.DateField(blank=True, db_column='Date_Submitted', null=True)),
                ('date_completed', models.DateField(blank=True, db_column='Date_Completed', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
                ('job_status', models.ForeignKey(db_column='Job_Status', on_delete=django.db.models.deletion.PROTECT, to='structure.JobStatus')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order')),
                ('procedures', models.ManyToManyField(to='structure.Procedure')),
            ],
            options={
                'permissions': (('view_job', 'Can view job'),),
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('date_received', models.DateField(blank=True, db_column='Date_Received', null=True)),
                ('location', models.CharField(db_column='Location', max_length=255)),
                ('storage', models.CharField(blank=True, db_column='Storage', max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_job', to='jobs.Job')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.Organism')),
                ('sample_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.SampleStatus')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.SampleType')),
            ],
            options={
                'permissions': (('view_sample', 'Can view sample'),),
            },
        ),
    ]
