# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(db_column='Job_ID', primary_key=True, serialize=False)),
                ('job_name', models.CharField(db_column='Job_Name', max_length=45)),
                ('date_submitted', models.DateField(blank=True, db_column='Date_Submitted', null=True)),
                ('date_completed', models.DateField(blank=True, db_column='Date_Completed', null=True)),
                ('job_status', models.CharField(choices=[('Q', 'Queued'), ('P', 'Processing'), ('S', 'Successful'), ('F', 'Failed'), ('C', 'Canceled')], db_column='Job_Status', default='Q', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('job_type_id', models.AutoField(db_column='Job_Type_ID', primary_key=True, serialize=False)),
                ('tag', models.CharField(db_column='Job_Tag', max_length=50)),
                ('type', models.CharField(db_column='Job_Type_Name', max_length=255)),
                ('note', models.TextField(blank=True, db_column='Job_Note', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(db_column='Job_Type', on_delete=django.db.models.deletion.PROTECT, to='jobs.JobType'),
        ),
    ]
