# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('view_job', 'Can view job'),)},
        ),
        migrations.AlterModelOptions(
            name='jobprocedure',
            options={'permissions': (('view_jobprocedure', 'Can view jobprocedure'),)},
        ),
    ]
