# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pre_tax_final'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='quote',
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='sample',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
        ),
    ]
