# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(db_column='Job_ID', on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('procedure_id', models.ForeignKey(db_column='Procedure_ID', on_delete=django.db.models.deletion.PROTECT, to='jobs.Procedure')),
            ],
        ),
    ]
