# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobprocedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprocedure',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='jobprocedure',
            name='procedure_id',
        ),
        migrations.AddField(
            model_name='jobprocedure',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprocedure',
            name='procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jobs.Procedure'),
            preserve_default=False,
        ),
    ]
