# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20160726_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='is_active',
            field=models.BooleanField(db_column='Is_Active', default=True),
        ),
    ]
