# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.AutoField(db_column='ClientID', primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_column='Last_Name', max_length=45)),
                ('first_name', models.CharField(db_column='First_Name', max_length=45)),
                ('customer_id', models.IntegerField(blank=True, db_column='Customer ID', null=True, unique=True)),
                ('company', models.TextField(blank=True, db_column='Company', null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=10, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=30, null=True)),
                ('cell_phone', models.CharField(blank=True, db_column='Cell_Phone', max_length=25, null=True)),
                ('work_phone', models.CharField(blank=True, db_column='Work_Phone', max_length=25, null=True)),
                ('alt_phone', models.CharField(blank=True, db_column='Alt_Phone', max_length=25, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=25, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('zip', models.CharField(blank=True, db_column='ZIP', max_length=20, null=True)),
                ('poochon_rep', models.CharField(blank=True, db_column='Poochon_Rep', max_length=45, null=True)),
            ],
            options={
                'permissions': (('view_client', 'Can view client'),),
                'managed': True,
            },
        ),
    ]
