# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True, 'permissions': (('view_client', 'Can view client'),)},
        ),
    ]
