# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('view_item', 'Can view items'), ('add_edit_item', 'Can add/edit items'), ('delete_item', 'Can delete items'))},
        ),
    ]
