# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160728_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('view_item', 'Can view item'),)},
        ),
    ]
