# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('job_type_id', models.AutoField(db_column='Job_Type_ID', primary_key=True, serialize=False)),
                ('tag', models.CharField(db_column='Job_Tag', max_length=50)),
                ('type', models.CharField(db_column='Job_Type_Name', max_length=255)),
                ('note', models.TextField(blank=True, db_column='Job_Note', null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('procedure_id', models.AutoField(db_column='Procedure_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
            ],
        ),
    ]
