# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'permissions': (('view_ItemCategory', 'Can view ItemCategory'),)},
        ),
        migrations.AlterModelOptions(
            name='jobstatus',
            options={'permissions': (('view_jobstatus', 'Can view jobstatus'),)},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'permissions': (('view_jobtype', 'Can view jobtype'),)},
        ),
        migrations.AlterModelOptions(
            name='organism',
            options={'permissions': (('view_organism', 'Can view organism'),)},
        ),
        migrations.AlterModelOptions(
            name='paymentterm',
            options={'permissions': (('view_paymentterm', 'Can view paymentterm'),)},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'permissions': (('view_procedure', 'Can view procedure'),)},
        ),
        migrations.AlterModelOptions(
            name='quotestatus',
            options={'permissions': (('view_quotestatus', 'Can view quotestatus'),)},
        ),
        migrations.AlterModelOptions(
            name='samplestatus',
            options={'permissions': (('view_samplestatus', 'Can view samplestatus'),)},
        ),
        migrations.AlterModelOptions(
            name='sampletype',
            options={'permissions': (('view_sampletype', 'Can view sampletype'),)},
        ),
    ]
