# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.Quote'),
        ),
    ]
