# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pre_tax_final',
            field=models.FloatField(db_column='Pre_Tax_Final', default=1),
            preserve_default=False,
        ),
    ]
