# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        ('orders', '0002_order_pre_tax_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.Quote'),
        ),
    ]
