# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('quote_date', models.DateField(db_column='Quote_Date')),
                ('expire_date', models.DateField(db_column='Expire_Date')),
                ('sample_number', models.IntegerField(db_column='Sample_Number')),
                ('pre_tax_final', models.FloatField(db_column='Pre_Tax_Final')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.PaymentTerm')),
                ('service_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.ServicePackage')),
                ('services', models.ManyToManyField(blank=True, to='structure.Service')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.QuoteStatus')),
            ],
            options={
                'permissions': (('view_quote', 'Can view quote'),),
            },
        ),
    ]
