# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.AutoField(db_column='Job_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_client', to='clients.Client')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.ForeignKey(db_column='Job_ID', on_delete=django.db.models.deletion.CASCADE, to='quotes.Quote')),
            ],
        ),
    ]
