# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20160728_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': (('view_quote', 'Can view quote'),)},
        ),
        migrations.AlterModelOptions(
            name='quoteprocedure',
            options={'permissions': (('view_quoteprocedure', 'Can view quoteprocedure'),)},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'permissions': (('view_sample', 'Can view sample'),)},
        ),
    ]
